Update README.md
criadoperez/gitdao pull request #1
Opened 2024-03-21 14:50 UTC by treboryatska

Adjusted intro section format to problem/solution. Reworked the mission section. Moved main TLDR/Why to top sentence in Why Gitdao section, and shortened the section.

2024-03-25 17:23 UTC, criadoperez requested changes
Thanks @treboryatska 
Could you make some changes?

2024-03-25 17:23 UTC, criadoperez commented on README.md
> +With GitDAO, you can set predefined governance rules for the founders and contributors. This allows governance control percentages to be realocated as the project grows and evolves.
I like your definition. Can you add it without deleting the other part?

2024-03-25 17:23 UTC, criadoperez commented on README.md
> +Gitdao is an objective framework that enables real project stewardship and asset ownership for developers providing real contributions.
The sentence you are replacing talks about future objectives, which goes far beyond contributions.
Your sentence is a definition if what is is now in this first stage.
Can we maybe add both?

2024-03-25 17:23 UTC, criadoperez commented on README.md
> +Enable credibly neutral governance models for free and open source software (FOSS) projects.
Can you also add the word "decentralize" somewhere in your definition? (it's an important aspect of it)

2024-03-26 10:59 UTC, treboryatska commented on README.md
> +Create objective tools any project can use to easily assign project ownership to contributors.
Can you expand on your vision for how ownership can be distributed to investors/users in a gitDAO?

2024-03-26 11:00 UTC, treboryatska commented on README.md
> +Today, developers have little control of the roadmaps they contribute to, and no control of the project's assets, such as the code repository, website, social media content accounts, domains and lice
Yep, that works. What is the best way to make this change?

2024-03-26 11:12 UTC, treboryatska commented on README.md
> +Enable credibly neutral governance models for free and open source software (FOSS) projects.
I view "decentralization" as simply one way to build something that is credibly neutral. But, I get that decentralization is a more common understanding of what we want to achieve. I can say "Enable decentralized and credibly neutral governance models..."

2024-03-26 11:25 UTC, treboryatska commented on README.md
> +With GitDAO, you can set predefined governance rules for the founders and contributors. This allows governance control percentages to be realocated as the project grows and evolves.
The most important change I made in this *why* section was moving the TLDR to the first sentence. We should keep that change. Otherwise, I mostly just restructured what you had written.

2024-03-27 00:21 UTC, criadoperez commented on README.md
> +Create objective tools any project can use to easily assign project ownership to contributors.
Let's imagine for example that an investor wants to invest a specific amount in the project.
Any member of the DAO could make a proposal on the DAO's dashboard, of minting a number of tokens to an investor's wallet in exchange a certain amount of money (USDCs for example). 
Once the proposal is created, the members will need to vote to see if they accept the investors offer. 
If the proposal gets approved, the new tokens will get minted to a smart contract awaiting payment.
Then the investor can transfer USDC to the smart contract to obtain the tokens in exchange.

2024-03-27 00:28 UTC, criadoperez commented on README.md
> +Today, developers have little control of the roadmaps they contribute to, and no control of the project's assets, such as the code repository, website, social media content accounts, domains and lice
```
Gitdao allows contributors of a Git repository to be the owners of the repository using a DAO.

Today, most developers have little control of the roadmaps they contribute to, and no control of the project's assets, such as the code repository, website, social media content accounts, domains and licensing, and funding.
```

2024-03-27 00:29 UTC, criadoperez commented on README.md
> +Enable credibly neutral governance models for free and open source software (FOSS) projects.
that works.

2024-03-27 14:04 UTC, treboryatska commented on README.md
> +Create objective tools any project can use to easily assign project ownership to contributors.
Can you help me understand how this is different from existing token governance models?

2024-03-27 15:25 UTC, treboryatska commented on README.md
> +Enable credibly neutral governance models for free and open source software (FOSS) projects.
Should be updated in patch 1

2024-03-27 15:26 UTC, treboryatska commented on README.md
> +Today, developers have little control of the roadmaps they contribute to, and no control of the project's assets, such as the code repository, website, social media content accounts, domains and lice
Should be updated in patch-1

2024-03-27 15:42 UTC, treboryatska commented on README.md
> +Create objective tools any project can use to easily assign project ownership to contributors.
Just following up on our conversation. I still feel the mission statement is too broad. Are we setting out to build objective tools for assigning ownership contributors, founders, investors, users? Or, does the objective tool used for assigning ownership to contributors need to account for non-contributor owners?

2024-03-27 17:29 UTC, merged